spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sights
    username: root
    driver-class-name: org.postgresql.Driver
    password: 123
  liquibase:
    change-log: classpath:database/changelog/db.changelog-master.xml